name: "My GitHub Action"

on:
    push:
    branch:
        -main
    
jobs:
    demo:
        runs-on: ubuntu-latest
        steps:
            -name: "print hello world"
                run: echo "hello world"