name: "hello-workflow"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print message
        run: echo "Hello, world! This is a GitHub Actions workflow."
      
      - name: List files
        run: ls -la